sudo: false
language: node_js
node_js:
  - "node"
  - "4"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper-.*$/
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
after_script:
  - npm run report-coverage
  - npm run semantic-release
notifications:
  email: change
