language: node_js
node_js:
- stable
- iojs
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
script: gulp
after_script:
  - codeclimate-test-reporter < reports/lcov.info
deploy:
  provider: npm
  email: admin@arxstudios.net
  api_key:
    secure: FPoYvp2dH5Cvu2PyJQUuh5wHYFQMGQOpCF/gtCIJVFDysoguzM48DVv8ih5mGa231UWuMflYOAw5FSL5yzJIssqP88jnLfJ7U0Cng67yAIRAg1hC1vQy0QFxU/G9MB2fq8GhvAWlw6RCqUtvqlhavr/iGYgqRYx/fTtOQ2CnXSRu/Ws2/xURJloQ/dCGAGg5kHDqNhpbBLDDMi2YsWRS7Ih3QTkqi2dlOG7sCemxrMQ2ntboLX3I5QYSFVBZYXJeHPKZGiWKMzDlzGZEGFjGOAcXk2GqRik4HH6QIf85Abt3EZ7k8WpBqx/IrLBC9OJwFJwuoZO+97PoQj9piQGIl5VvDyTsgAaCjdlj3v6WxWM++e7KUNxkGuzTAV0WbdGCWHn0PXC159oUxABfmmNPbNY22C+/waAaavVNsB7ZEdW30Y8CibzGe+5VDG8rYehArxValuXz/KSeB3qDNjGixg3kb3bS31+4rrQmz1mepYVWO/WGjEnpSTYOWdalAfdx0dsxC2tLLQvg68UUtcnkDS80i/Uo8RmKLGAQX7t0NuO0tIWOzVPhWxei79AnvRzkKu84odYCN1b8DEoFbetDDdFizm/3livg3iKfwjMYEXKFZ6+CB8VKcguL6DSTX1MnXivD6VNByESKffA6PreaTyAvyL8v840+Zb3yL8TnuLU=
  on:
    branch: master
    tags: true
notifications:
  slack:
    secure: ENKTdT08GhdFVnwUYfNp/S9/vdLjSettDlYKBNW1R4loPu8Z55n/fpQGvvvgm+G+aZrcEZb+pK9+ZmeLPm4dU1aCYILqAKHY90940XzyM7Xx5N7xnPl2LDwWhbXO8o5vYN0CJZksv3JBN8waUjNgpGKMX47kmSv9/uqec+1oKjExQCuIjpBm3DrGufh3pxCHc3bCacBba/hlnVMI9MWsdv7/UxExnKfOB5Z1nR67sJoRosBUo+UhZJZMcprcBk7XE+3py9xkW6LrbR2a60MguvVQTdTOEVX904e0ccttAzOZiYqFH/qaQ5iqKOuOUojNqHV7wHgm/Lw5a6mTSSEucYdyWdO6VYrn2LnWB0VKQHyqg07MzaVp85o49dR77+VgV3MEhqVHkLtTGr8tC1UPwSzUwurmu8l26TTiwfPCq0fBDc51q+kTVb2tJ48obUuXTmPkU+QqiG1m/1CAPLYOl8GwDPrWq9nNkQ12nDvfk7iumBBAsNc4+U/EZ9U2zzrQ30j9XsI1ukFinH5U8XeJSmKZae0+ddT+mTdM2X5M9O6QEqDg6N6/k/PvizkafhdxzwD1Wn89syRx7mrF84kLfbdQPBXaCEQ+/Sz1XL5tvUFjinJsEnWGQ08YZ7evWp0nOlisyGrAheo1PiAYvAxvMid1TpEjvC7VHOdJxHXybeI=
    on_success: change  # options: [always|never|change] default: always
  email: false
addons:
    code_climate:
        repo_token: 358bf77c342d05aabfc52308759fca1eae709862f455993a3c3de8a4530cda2a
